name: 更新帮助网站

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install coscmd
        run: sudo pip install coscmd
            
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: helppage-1306537081
          REGION: ap-beijing
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        
      - name: Delete Old Files & Update
        run: |
          coscmd delete -r / -f
          coscmd upload -r /home/runner/work/ysserver-helpppage /
