name: Update Website

on:
  push:
    branches:
      - main
  workflow_dispatch: 


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 签出仓库
        uses: actions/checkout@v3

      - name: 安装阿里云 ossutil
        run: |
          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash

      - name: 配置 ossutil
        run: |
          ossutil config -L CH -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}